[package]
name = "dispatch-proxy"
version = "0.1.1-alpha.0"
authors = ["Alexandre Kirszenberg <alex@kirszenberg.com>"]
edition = "2018"
description = "A SOCKS proxy that balances traffic between network interfaces."
license = "MIT OR Apache-2.0"
keywords = ["SOCKS", "proxy", "dispatch", "network", "interface"]
repository = "https://github.com/alexkirsz/dispatch"

[[bin]]
path = "src/main.rs"
name = "dispatch"

[profile.release]
debug = true

[dependencies]
socksv5 = { version = "0.3.0", features = ["tokio"], default-features = false }
tracing = "0.1.26"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.19"
tracing-error = "0.1.2"
tracing-appender = "0.1.2"
eyre = "0.6.5"
color-eyre = { version = "0.5.11", features = ["issue-url"] }
tokio = { version = "1.8", features = [
  "macros",
  "net",
  "rt-multi-thread",
  "io-util"
] }
structopt = "0.3.21"
pnet_datalink = "0.28.0"
owo-colors = "2.0.0"
tokio-util = "0.6.7"
async-trait = "0.1.50"
directories = "3.0.2"
percent-encoding = "2.1.0"
term-table = "1.3.1"
sysinfo = "0.19.2"
